# Generated by Django 5.2.15 on 2026-07-06 18:57

import django.db.models.deletion
import servicenow.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNowCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(help_text='Es. CS0628228', max_length=50, verbose_name='Numero case')),
                ('account', models.CharField(max_length=255, verbose_name='Account')),
                ('priority', models.CharField(choices=[('1', '1 - Critical'), ('2', '2 - High'), ('3', '3 - Moderate'), ('4', '4 - Low')], default='3', max_length=20, verbose_name='Priorità')),
                ('opened_date', models.DateField(blank=True, null=True, verbose_name='Data apertura')),
                ('short_description', models.TextField(blank=True, verbose_name='Descrizione breve')),
                ('screenshot', models.ImageField(blank=True, null=True, upload_to=servicenow.models.servicenow_screenshot_upload_path, verbose_name='Screenshot')),
                ('status', models.CharField(choices=[('open', 'Aperto'), ('in_progress', 'In lavorazione'), ('closed', 'Chiuso')], default='open', max_length=20, verbose_name='Stato interno')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_servicenow_cases', to=settings.AUTH_USER_MODEL, verbose_name='Assegnato a')),
            ],
            options={
                'verbose_name': 'ServiceNow Case',
                'verbose_name_plural': 'ServiceNow Case',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='sncase_status_idx'), models.Index(fields=['priority'], name='sncase_priority_idx'), models.Index(fields=['assigned_to'], name='sncase_assigned_idx'), models.Index(fields=['deleted_at'], name='sncase_deleted_at_idx'), models.Index(fields=['-created_at'], name='sncase_created_at_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('number',), name='ux_servicenow_case_number_active')],
            },
        ),
    ]
