# Generated by Django 5.2.15 on 2026-07-06 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicenow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenowcase',
            name='case_type',
            field=models.CharField(choices=[('cdd', 'CDD'), ('privati', 'PRIVATI'), ('l1', 'L1')], default='cdd', max_length=20, verbose_name='Type'),
        ),
        migrations.AddIndex(
            model_name='servicenowcase',
            index=models.Index(fields=['case_type'], name='sncase_case_type_idx'),
        ),
    ]
