# Generated by Django 5.2.16 on 2026-07-11 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicenow', '0007_servicenowcase_swap_case_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TechnicianAbsence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.DateField(verbose_name='Dal')),
                ('date_to', models.DateField(verbose_name='Al')),
                ('reason', models.CharField(choices=[('ferie', 'Ferie'), ('malattia', 'Malattia'), ('trasferta', 'Trasferta'), ('altro', 'Altro')], default='ferie', max_length=20, verbose_name='Motivo')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Nota')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Creato da')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicenow_absences', to=settings.AUTH_USER_MODEL, verbose_name='Tecnico')),
            ],
            options={
                'verbose_name': 'Assenza tecnico',
                'verbose_name_plural': 'Assenze tecnici',
                'ordering': ['-date_from'],
                'indexes': [models.Index(fields=['user', 'date_from', 'date_to'], name='sn_absence_user_range_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('date_to__gte', models.F('date_from'))), name='ck_technician_absence_date_range')],
            },
        ),
    ]
