# Generated by Django 5.2.16 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicenow', '0008_technicianabsence'),
    ]

    operations = [
        migrations.AddField(
            model_name='technicianabsence',
            name='time_from',
            field=models.TimeField(blank=True, help_text="Valorizzare insieme a Ora fine solo per un'assenza oraria (permesso) su un singolo giorno.", null=True, verbose_name='Ora inizio'),
        ),
        migrations.AddField(
            model_name='technicianabsence',
            name='time_to',
            field=models.TimeField(blank=True, null=True, verbose_name='Ora fine'),
        ),
    ]
