# Generated by Django 5.2.16 on 2026-07-17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicenow', '0009_technicianabsence_time_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenowcase',
            name='opened_time',
            field=models.TimeField(blank=True, help_text='Richiesta lato form quando è impostata la data apertura (non estratta via OCR).', null=True, verbose_name='Ora apertura'),
        ),
    ]
