# Generated by Django 5.2.17 on 2026-09-08 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_rename_notificatio_recipie_1a2b3c_idx_notificatio_recipie_4e3567_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='last_emailed_event_date',
            field=models.DateField(blank=True, help_text="event_date per cui è già stata inviata l'email digest di refresh_notifications. Usato per non reinviare l'email a ogni refresh: si reinvia solo quando event_date cambia rispetto a questo valore.", null=True),
        ),
    ]
