services:
  caddy:
    volumes:
      - ./deploy/Caddyfile.prod:/etc/caddy/Caddyfile:ro

  db:
    env_file:
      - ./.env.prod

  backend:
    env_file:
      - ./.env.prod

  cron:
    env_file:
      - ./.env.prod

  frontend-auslbo:
    build:
      context: .
      dockerfile: frontend-auslbo/Dockerfile
