services:
  caddy:
    volumes:
      - ./deploy/Caddyfile.dev:/etc/caddy/Caddyfile:ro

  db:
    env_file:
      - ./.env.dev

  backend:
    env_file:
      - ./.env.dev

  cron:
    env_file:
      - ./.env.dev

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
      args:
        VITE_APP_ENV: development

  frontend-portal:
    build:
      context: .
      dockerfile: frontend-portal/Dockerfile
      args:
        VITE_APP_ENV: development
