# Generated by Django 5.2.11 on 2026-02-09 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('schedule_type', models.CharField(choices=[('interval', 'Interval'), ('fixed_date', 'Fixed date')], max_length=16)),
                ('interval_unit', models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], max_length=16, null=True)),
                ('interval_value', models.PositiveIntegerField(blank=True, null=True)),
                ('fixed_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fixed_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('default_alert_days_before', models.PositiveIntegerField(default=14)),
                ('notes', models.TextField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_templates', to='core.inventorytype')),
                ('default_tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='default_templates', to='maintenance.tech')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('schedule_type', models.CharField(choices=[('interval', 'Interval'), ('fixed_date', 'Fixed date')], max_length=16)),
                ('interval_unit', models.CharField(blank=True, choices=[('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], max_length=16, null=True)),
                ('interval_value', models.PositiveIntegerField(blank=True, null=True)),
                ('fixed_month', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fixed_day', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('next_due_date', models.DateField()),
                ('last_done_date', models.DateField(blank=True, null=True)),
                ('alert_days_before', models.PositiveIntegerField(default=14)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('custom_fields', models.JSONField(blank=True, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_plans', to='inventory.inventory')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='maintenance.maintenancetemplate')),
                ('tech', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='plans', to='maintenance.tech')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('performed_at', models.DateField()),
                ('result', models.CharField(choices=[('ok', 'OK'), ('ko', 'KO'), ('partial', 'Partial')], max_length=16)),
                ('notes', models.TextField(blank=True, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_events', to='inventory.inventory')),
                ('plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='events', to='maintenance.maintenanceplan')),
                ('tech', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='maintenance.tech')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaintenanceNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_date', models.DateField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('recipient_internal', models.EmailField(max_length=254)),
                ('recipient_tech', models.EmailField(max_length=254)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=16)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='inventory.inventory')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='notifications', to='maintenance.maintenanceplan')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('plan', 'due_date'), name='ux_maint_notif_plan_due_active')],
            },
        ),
    ]
