# Generated by Django 5.2.11 on 2026-02-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenanceevent',
            options={'verbose_name': 'Rapportino', 'verbose_name_plural': 'Rapportini'},
        ),
        migrations.AlterModelOptions(
            name='maintenancenotification',
            options={'verbose_name': 'Notifica manutenzione', 'verbose_name_plural': 'Notifica manutenzioni'},
        ),
        migrations.AlterModelOptions(
            name='maintenanceplan',
            options={'verbose_name': 'Piano manutenzione', 'verbose_name_plural': 'Piani manutenzioni'},
        ),
        migrations.AlterModelOptions(
            name='maintenancetemplate',
            options={'verbose_name': 'Template manutenzioni', 'verbose_name_plural': 'Template manutenzioni'},
        ),
        migrations.AlterModelOptions(
            name='tech',
            options={'verbose_name': 'Tecnico', 'verbose_name_plural': 'Tecnici'},
        ),
    ]
