# Generated by Django 5.2.11 on 2026-02-22 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_restructure_maintenance'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancenotification',
            options={'verbose_name': 'Notifica manutenzione', 'verbose_name_plural': 'Notifiche manutenzioni'},
        ),
    ]
