# Generated by Django 5.2.11 on 2026-02-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0005_maintenanceevent_pdf_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenanceevent',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='maintenance_events/'),
        ),
    ]
