# Generated by Django 5.2.11 on 2026-02-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contatto', 'verbose_name_plural': 'Contatti'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Cliente', 'verbose_name_plural': 'Clienti'},
        ),
        migrations.AlterModelOptions(
            name='site',
            options={'verbose_name': 'Sito', 'verbose_name_plural': 'Siti'},
        ),
    ]
