# Generated by Django 5.2.11 on 2026-02-14 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_site_display_name_and_field_renames'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='contact',
            name='ux_contacts_primary_per_scope',
        ),
    ]
