# Generated by Django 5.2.16 on 2026-07-24 15:42

from django.db import migrations


def rename_permission(apps, schema_editor):
    # AlterModelOptions aggiorna solo lo stato delle migration: il nome del
    # permesso già creato in tabella auth_permission va rinominato a mano
    # (create_permissions, il signal post_migrate, crea solo quelli mancanti).
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    try:
        ct = ContentType.objects.get(app_label="crm", model="customervpnaccess")
    except ContentType.DoesNotExist:
        return
    Permission.objects.filter(content_type=ct, codename="view_vpn_secrets").update(
        name="Può visualizzare le credenziali VPN (password)"
    )


def rename_permission_reverse(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    try:
        ct = ContentType.objects.get(app_label="crm", model="customervpnaccess")
    except ContentType.DoesNotExist:
        return
    Permission.objects.filter(content_type=ct, codename="view_vpn_secrets").update(
        name="Can view VPN secrets (password)"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0008_customer_vpn_access'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customervpnaccess',
            options={'permissions': [('view_vpn_secrets', 'Può visualizzare le credenziali VPN (password)')], 'verbose_name': 'Accesso VPN Cliente', 'verbose_name_plural': 'Accessi VPN Clienti'},
        ),
        migrations.RunPython(rename_permission, rename_permission_reverse),
    ]
