# Generated by Django 5.2.11 on 2026-02-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wikiattachment',
            options={'verbose_name': 'Allegato', 'verbose_name_plural': 'Allegati'},
        ),
        migrations.AlterModelOptions(
            name='wikicategory',
            options={'verbose_name': 'Categoria', 'verbose_name_plural': 'Categorie'},
        ),
        migrations.AlterModelOptions(
            name='wikilink',
            options={'verbose_name': 'Link', 'verbose_name_plural': 'Links'},
        ),
        migrations.AlterModelOptions(
            name='wikipage',
            options={'verbose_name': 'Pagina', 'verbose_name_plural': 'Pagine'},
        ),
    ]
