# Generated by ChatGPT on 2026-02-25
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("wiki", "0002_alter_wikiattachment_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="wikipage",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="children",
                to="wiki.wikipage",
            ),
        ),
    ]
