# Generated by Django 5.2.11 on 2026-02-27 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0004_wikicategory_emoji_color_wikiattachment_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wikiattachment',
            name='storage_key',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
    ]
