# Generated by Django 5.2.16 on 2026-07-25 13:21

import django.db.models.deletion
import purchaseorders.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0009_alter_customervpnaccess_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseOrderEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('offer_date', models.DateField(verbose_name='Data offerta')),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('client_name', models.CharField(max_length=255, verbose_name='Committente')),
                ('purchase_order', models.CharField(blank=True, max_length=128, verbose_name='Purchase Order')),
                ('invoice_number', models.CharField(blank=True, max_length=128, verbose_name='N. Fattura')),
                ('kind', models.CharField(choices=[('ordinario', 'Ordinario'), ('extra', 'Extra')], default='extra', max_length=16, verbose_name='Tipo')),
                ('status', models.CharField(choices=[('inserito', 'Inserito'), ('inviato', 'Inviato'), ('ricevuto', 'Ricevuto'), ('fatturato', 'Fatturato')], default='inserito', max_length=16, verbose_name='Stato')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Data invio offerta')),
                ('received_at', models.DateTimeField(blank=True, null=True, verbose_name='Data ricezione PO')),
                ('invoiced_at', models.DateTimeField(blank=True, null=True, verbose_name='Data fatturazione')),
                ('offer_document', models.FileField(blank=True, null=True, upload_to=purchaseorders.models.offer_document_upload_path, verbose_name='PDF Offerta')),
                ('po_document', models.FileField(blank=True, null=True, upload_to=purchaseorders.models.po_document_upload_path, verbose_name='PDF Purchase Order')),
                ('invoice_document', models.FileField(blank=True, null=True, upload_to=purchaseorders.models.invoice_document_upload_path, verbose_name='PDF Fattura')),
                ('amount_mode', models.CharField(choices=[('fisso', 'Valore fisso'), ('giornate', 'Giornate × tariffa')], default='fisso', max_length=16, verbose_name='Modalità importo')),
                ('days', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='Giornate')),
                ('daily_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Tariffa/giorno')),
                ('amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='Importo')),
                ('costs_incurred', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Costi sostenuti')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_order_entries', to='crm.customer', verbose_name='Cliente')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Purchase Order',
                'verbose_name_plural': 'Purchase Order',
                'ordering': ['-offer_date', '-created_at'],
                'indexes': [models.Index(fields=['kind'], name='po_entry_kind_idx'), models.Index(fields=['status'], name='po_entry_status_idx'), models.Index(fields=['customer'], name='po_entry_customer_idx'), models.Index(fields=['offer_date'], name='po_entry_offer_date_idx'), models.Index(fields=['deleted_at'], name='po_entry_deleted_at_idx'), models.Index(fields=['-created_at'], name='po_entry_created_at_idx')],
            },
        ),
    ]
