# Generated by Django 5.2.16 on 2026-07-25 13:40

import purchaseorders.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0009_alter_customervpnaccess_options'),
        ('purchaseorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderentry',
            name='invoice_document',
            field=models.FileField(blank=True, null=True, upload_to=purchaseorders.models.invoice_document_upload_path, verbose_name='PDF Fattura'),
        ),
        migrations.AddField(
            model_name='purchaseorderentry',
            name='invoiced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data fatturazione'),
        ),
        migrations.AddField(
            model_name='purchaseorderentry',
            name='offer_document',
            field=models.FileField(blank=True, null=True, upload_to=purchaseorders.models.offer_document_upload_path, verbose_name='PDF Offerta'),
        ),
        migrations.AddField(
            model_name='purchaseorderentry',
            name='po_document',
            field=models.FileField(blank=True, null=True, upload_to=purchaseorders.models.po_document_upload_path, verbose_name='PDF Purchase Order'),
        ),
        migrations.AddField(
            model_name='purchaseorderentry',
            name='received_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data ricezione PO'),
        ),
        migrations.AddField(
            model_name='purchaseorderentry',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data invio offerta'),
        ),
        migrations.AddField(
            model_name='purchaseorderentry',
            name='status',
            field=models.CharField(choices=[('inserito', 'Inserito'), ('inviato', 'Inviato'), ('ricevuto', 'Ricevuto'), ('fatturato', 'Fatturato')], default='inserito', max_length=16, verbose_name='Stato'),
        ),
        migrations.AddIndex(
            model_name='purchaseorderentry',
            index=models.Index(fields=['status'], name='po_entry_status_idx'),
        ),
    ]
