# Generated by Django 5.2.16 on 2026-07-25 13:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    # Fix (2026-07-28): questa migrazione originariamente aggiungeva questi
    # campi/indice sopra una versione più vecchia di 0001_initial. In seguito
    # 0001_initial è stata rigenerata includendo già questi stessi campi
    # (offer_document, invoice_document, po_document, sent_at, received_at,
    # invoiced_at, status, indice po_entry_status_idx — vedi 0001_initial.py),
    # ma questa migrazione incrementale non è stata rimossa/svuotata.
    # Su ambienti dove 0001+0002 sono già stati applicati storicamente non
    # cambia nulla (Django non ri-applica migrazioni già segnate come
    # eseguite). Su un install/migrate da zero, invece, 0002 falliva con
    # "column already exists" perché tentava di ri-creare ciò che 0001
    # aveva già creato. Svuotata a no-op: resta nella storia delle
    # migrazioni (0003 dipende da questo nome) ma non fa più nulla.

    dependencies = [
        ('crm', '0009_alter_customervpnaccess_options'),
        ('purchaseorders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = []
