# Generated by Django 5.2.16 on 2026-07-25 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchaseorders', '0002_purchaseorderentry_invoice_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderentry',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Note'),
        ),
    ]
