# Generated by Django 5.2.11 on 2026-03-01 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_issue_opened_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='opened_at',
        ),
        migrations.AlterField(
            model_name='issue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='servicenow_id',
            field=models.CharField(blank=True, help_text='Es. INC0012345', max_length=100, verbose_name='Caso ServiceNow'),
        ),
        migrations.AlterField(
            model_name='issuecategory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='issuecomment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
