# Generated by Django 5.2.11 on 2026-03-01 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_remove_issue_opened_at_alter_issue_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='opened_at',
            field=models.DateField(blank=True, null=True, verbose_name='Data apertura'),
        ),
    ]
