# Generated by Django 5.2.11 on 2026-02-09 16:57

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('knumber', models.CharField(blank=True, max_length=64, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=128, null=True)),
                ('os_user', models.CharField(blank=True, max_length=128, null=True)),
                ('os_pwd', models.CharField(blank=True, max_length=128, null=True)),
                ('app_usr', models.CharField(blank=True, max_length=128, null=True)),
                ('app_pwd', models.CharField(blank=True, max_length=128, null=True)),
                ('vnc_pwd', models.CharField(blank=True, max_length=128, null=True)),
                ('hostname', models.CharField(blank=True, max_length=255, null=True)),
                ('local_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('srsa_ip', models.CharField(blank=True, max_length=64, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=128, null=True)),
                ('model', models.CharField(blank=True, max_length=128, null=True)),
                ('warranty_end_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ('custom_fields', models.JSONField(blank=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='crm.customer')),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventories', to='crm.site')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.inventorystatus')),
                ('type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.inventorytype')),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('knumber__isnull', False)), fields=('knumber',), name='ux_inventories_knumber_active'), models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('serial_number__isnull', False)), fields=('serial_number',), name='ux_inventories_serial_active')],
            },
        ),
    ]
