# Generated by Django 5.2.11 on 2026-02-19 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventory_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={
                'constraints': [
                    models.UniqueConstraint(
                        condition=models.Q(
                            ('deleted_at__isnull', True),
                            ('knumber__isnull', False),
                        ),
                        fields=('knumber',),
                        name='ux_inventories_knumber_active',
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ('deleted_at__isnull', True),
                            ('serial_number__isnull', False),
                        ),
                        fields=('serial_number',),
                        name='ux_inventories_serial_active',
                    ),
                ],
                'permissions': [
                    ('view_secrets', 'Can view inventory secrets'),
                ],
            },
        ),
    ]
