# Generated by Django 5.2.16 on 2026-07-24 15:42

from django.db import migrations


def rename_permission(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    try:
        ct = ContentType.objects.get(app_label="inventory", model="inventory")
    except ContentType.DoesNotExist:
        return
    Permission.objects.filter(content_type=ct, codename="view_secrets").update(
        name="Può visualizzare le credenziali riservate dell'inventario"
    )


def rename_permission_reverse(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    try:
        ct = ContentType.objects.get(app_label="inventory", model="inventory")
    except ContentType.DoesNotExist:
        return
    Permission.objects.filter(content_type=ct, codename="view_secrets").update(
        name="Can view inventory secrets"
    )


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_alter_inventory_knumber'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventory',
            options={'permissions': [('view_secrets', "Può visualizzare le credenziali riservate dell'inventario")]},
        ),
        migrations.RunPython(rename_permission, rename_permission_reverse),
    ]
