# Generated by ChatGPT (hand-written) for inventory-app

from django.db import migrations, models
import django.contrib.postgres.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomFieldDefinition",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("entity", models.CharField(choices=[("customer", "Cliente"), ("site", "Sito"), ("inventory", "Inventario")], max_length=32)),
                ("key", models.SlugField(max_length=64)),
                ("label", models.CharField(max_length=128)),
                ("field_type", models.CharField(choices=[("text", "Testo"), ("number", "Numero"), ("date", "Data"), ("select", "Selezione"), ("boolean", "Boolean")], default="text", max_length=16)),
                ("required", models.BooleanField(default=False)),
                ("options", models.JSONField(blank=True, null=True)),
                ("aliases", django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None)),
                ("help_text", models.CharField(blank=True, max_length=255, null=True)),
                ("sort_order", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("is_sensitive", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Campo custom",
                "verbose_name_plural": "Campi custom",
                "ordering": ["entity", "sort_order", "label", "key"],
            },
        ),
        migrations.AddConstraint(
            model_name="customfielddefinition",
            constraint=models.UniqueConstraint(condition=models.Q(("deleted_at__isnull", True)), fields=("entity", "key"), name="ux_customfielddefinition_entity_key_active"),
        ),
    ]
