# Generated by Django 5.2.11 on 2026-02-22 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_fields', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfielddefinition',
            name='entity',
            field=models.CharField(choices=[('customer', 'Cliente'), ('site', 'Sito'), ('inventory', 'Inventario'), ('maintenance_plan', 'Piano manutenzione')], max_length=32),
        ),
    ]
