# Generated by ChatGPT

from django.db import migrations, models


def compute_subject(ev, instance=None):
    app = getattr(ev.content_type, 'app_label', '') or ''
    model = getattr(ev.content_type, 'model', '') or ''

    def safe_get(obj, attr, default=None):
        if obj is None:
            return default
        return getattr(obj, attr, default)

    # Try instance-based rules
    if instance is not None:
        if app == 'crm' and model == 'contact':
            return (safe_get(instance, 'name') or safe_get(instance, 'email') or str(instance) or '').strip()

        if app == 'crm' and model == 'customer':
            return (safe_get(instance, 'name') or safe_get(instance, 'display_name') or str(instance) or '').strip()

        if app == 'crm' and model == 'site':
            site_name = (safe_get(instance, 'name') or safe_get(instance, 'display_name') or str(instance) or '').strip()
            cust = safe_get(instance, 'customer')
            cust_name = (safe_get(cust, 'name') or safe_get(cust, 'display_name') or '').strip() if cust else ''
            return f"{cust_name} - {site_name}".strip(' -') if cust_name else site_name

        if model == 'inventory':
            inv_name = (safe_get(instance, 'name') or safe_get(instance, 'hostname') or safe_get(instance, 'serial_number') or safe_get(instance, 'knumber') or str(instance) or '').strip()
            cust = safe_get(instance, 'customer')
            site = safe_get(instance, 'site')
            cust_name = (safe_get(cust, 'name') or safe_get(cust, 'display_name') or '').strip() if cust else ''
            site_name = (safe_get(site, 'name') or safe_get(site, 'display_name') or '').strip() if site else ''
            parts = [p for p in [inv_name, cust_name, site_name] if p]
            return ' - '.join(parts)

        if app == 'auth' and model == 'user':
            fn = (safe_get(instance, 'first_name') or '').strip()
            ln = (safe_get(instance, 'last_name') or '').strip()
            full = (f"{fn} {ln}").strip()
            return full or (safe_get(instance, 'username') or str(instance) or '').strip()

        return (str(instance) or '').strip()

    # Fallbacks when instance missing
    rep = (ev.object_repr or '').strip()

    # best-effort: customer __str__ is "C-000001 Name" -> keep only Name
    if app == 'crm' and model == 'customer' and rep.startswith('C-') and ' ' in rep:
        maybe_name = rep.split(' ', 1)[1].strip()
        if maybe_name:
            return maybe_name

    if rep:
        return rep

    oid = (ev.object_id or '').strip()
    return f"{app}.{model}({oid})" if (app and model and oid) else '—'


def backfill_subject(apps, schema_editor):
    AuditEvent = apps.get_model('audit', 'AuditEvent')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    qs = AuditEvent.objects.select_related('content_type').filter(subject='')

    for ev in qs.iterator(chunk_size=500):
        instance = None
        try:
            model_class = ev.content_type.model_class()
            if model_class is not None:
                instance = model_class.objects.filter(pk=ev.object_id).first()
        except Exception:
            instance = None

        subj = compute_subject(ev, instance=instance)[:512]
        AuditEvent.objects.filter(pk=ev.pk).update(subject=subj)


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='subject',
            field=models.CharField(blank=True, default='', max_length=512),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='action',
            field=models.CharField(
                choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('restore', 'Restore'), ('login', 'Login')],
                max_length=16,
            ),
        ),
        migrations.RunPython(backfill_subject, reverse_code=migrations.RunPython.noop),
    ]
