# Generated by Django 5.2.11 on 2026-02-17 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0002_subject_and_login'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_content_c1f818_idx',
            old_name='audit_audit_content_2aaf19_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_actor_i_58da28_idx',
            old_name='audit_audit_actor_i_a3b9d6_idx',
        ),
        migrations.RenameIndex(
            model_name='auditevent',
            new_name='audit_audit_action_0c0ad1_idx',
            old_name='audit_audit_action__0f40fa_idx',
        ),
    ]
