# Generated by ChatGPT on 2026-02-19
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0003_rename_audit_audit_content_2aaf19_idx_audit_audit_content_c1f818_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditevent",
            name="action",
            field=models.CharField(
                max_length=16,
                choices=[
                    ("create", "Create"),
                    ("update", "Update"),
                    ("delete", "Delete"),
                    ("restore", "Restore"),
                    ("login", "Login"),
                    ("login_failed", "Login Failed"),
                    ("logout", "Logout"),
                ],
            ),
        ),
    ]
