# Generated by Django 5.2.11 on 2026-02-09 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerstatus',
            options={'verbose_name': 'Customer status', 'verbose_name_plural': 'Customer Statuses'},
        ),
        migrations.AlterModelOptions(
            name='inventorystatus',
            options={'verbose_name': 'Inventory status', 'verbose_name_plural': 'Inventory Statuses'},
        ),
        migrations.AlterModelOptions(
            name='inventorytype',
            options={'verbose_name': 'Inventory type', 'verbose_name_plural': 'Inventory types'},
        ),
        migrations.AlterModelOptions(
            name='sitestatus',
            options={'verbose_name': 'Site status', 'verbose_name_plural': 'Site Statuses'},
        ),
    ]
