# Generated by Django 5.2.16 on 2026-07-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_is_philips'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_servicenow_technician',
            field=models.BooleanField(default=True, help_text="Se disattivato, l'utente non è assegnabile a nessun case ServiceNow (né Philips né Biotron) e non compare nel Triage / Statistiche. Impostabile solo da admin.", verbose_name='Tecnico ServiceNow'),
        ),
    ]
