# Generated by Django 6.0.7 on 2026-07-30 20:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_absence_request_group'),
        ('core', '0016_areatask'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='areatask',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='areatask',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_area_tasks', to=settings.AUTH_USER_MODEL, verbose_name='Ultima modifica di'),
        ),
        migrations.AddIndex(
            model_name='areatask',
            index=models.Index(fields=['deleted_at'], name='areatask_deleted_at_idx'),
        ),
        migrations.AddIndex(
            model_name='areatask',
            index=models.Index(fields=['area', 'deleted_at'], name='areatask_area_del_idx'),
        ),
    ]
