# Generated by Django 5.2.16 on 2026-07-30 20:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_areatask_softdelete_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64, unique=True, verbose_name='Chiave')),
                ('label', models.CharField(max_length=128, verbose_name='Etichetta')),
                ('allowed_w', models.JSONField(default=list, verbose_name='Larghezze ammesse')),
                ('allowed_h', models.JSONField(default=list, verbose_name='Altezze ammesse')),
                ('default_w', models.PositiveSmallIntegerField(verbose_name='Larghezza predefinita')),
                ('default_h', models.PositiveSmallIntegerField(verbose_name='Altezza predefinita')),
                ('sort_order', models.IntegerField(default=0, verbose_name='Ordine')),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
            ],
            options={
                'verbose_name': 'Widget dashboard',
                'verbose_name_plural': 'Widget dashboard',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='UserDashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField(default=0)),
                ('y', models.PositiveSmallIntegerField(default=0)),
                ('w', models.PositiveSmallIntegerField()),
                ('h', models.PositiveSmallIntegerField()),
                ('visible', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_layout_items', to=settings.AUTH_USER_MODEL)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_layouts', to='core.dashboardwidget')),
            ],
            options={
                'verbose_name': 'Layout dashboard utente',
                'verbose_name_plural': 'Layout dashboard utente',
                'constraints': [models.UniqueConstraint(fields=('user', 'widget'), name='uniq_user_dashboard_widget')],
            },
        ),
    ]
