# Generated by Django 5.2.16 on 2026-07-30 22:01
# Riordinata a mano rispetto all'output di makemigrations: aggiunge il nuovo
# campo, lo popola con le coppie [w,h] esplicite per ogni widget (non deriva
# dal prodotto cartesiano dei vecchi allowed_w/allowed_h, perché il meteo
# richiede combinazioni specifiche non cartesiane, es. 5x2 ma non 5x1), poi
# rimuove i vecchi campi.

from django.db import migrations, models

# widget_key -> lista di coppie [w, h] ammesse.
ALLOWED_SIZES = {
    'weather':       [[2, 1], [3, 1], [4, 1], [5, 2]],
    'contributor':   [[1, 2]],
    'issues':        [[2, 2], [2, 3], [3, 2], [3, 3], [4, 2], [4, 3]],
    'area-tasks':    [[2, 2], [2, 3], [3, 2], [3, 3], [4, 2], [4, 3]],
    'announcements': [[2, 1], [2, 2], [3, 1], [3, 2], [4, 1], [4, 2]],
    'todo':          [[2, 2], [2, 3], [3, 2], [3, 3], [4, 2], [4, 3]],
    'maintenance':   [[2, 2], [2, 3], [3, 2], [3, 3], [4, 2], [4, 3]],
}


def populate_allowed_sizes(apps, schema_editor):
    DashboardWidget = apps.get_model('core', 'DashboardWidget')
    UserDashboardLayout = apps.get_model('core', 'UserDashboardLayout')

    for key, sizes in ALLOWED_SIZES.items():
        DashboardWidget.objects.filter(key=key).update(allowed_sizes=sizes)

    # Layout utente già salvati con una coppia (w,h) non più tra quelle
    # ammesse (es. meteo salvato 5x1, ora non più valido): snap alla coppia
    # ammessa più vicina in distanza Manhattan, stesso criterio usato lato
    # frontend durante il resize.
    for widget in DashboardWidget.objects.filter(key__in=ALLOWED_SIZES.keys()):
        allowed = widget.allowed_sizes
        for row in UserDashboardLayout.objects.filter(widget=widget):
            if [row.w, row.h] in allowed:
                continue
            nearest = min(allowed, key=lambda p: abs(p[0] - row.w) + abs(p[1] - row.h))
            row.w, row.h = nearest
            row.save(update_fields=['w', 'h'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_fix_contributor_widget_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboardwidget',
            name='allowed_sizes',
            field=models.JSONField(default=list, verbose_name='Formati ammessi (coppie w,h)'),
        ),
        migrations.RunPython(populate_allowed_sizes, noop_reverse),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='allowed_h',
        ),
        migrations.RemoveField(
            model_name='dashboardwidget',
            name='allowed_w',
        ),
    ]
