# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_seed_sticky_note_widget'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(
                blank=True, null=True, verbose_name='Data di nascita',
                help_text="Usata dal widget dashboard 'Compleanni'. Impostabile solo da admin.",
            ),
        ),
    ]
