# Generated by Django 5.2.16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_resize_sticky_note_widget'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultDashboardLayout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.PositiveSmallIntegerField(default=0)),
                ('y', models.PositiveSmallIntegerField(default=0)),
                ('w', models.PositiveSmallIntegerField()),
                ('h', models.PositiveSmallIntegerField()),
                ('visible', models.BooleanField(default=True)),
                ('widget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='default_layout', to='core.dashboardwidget')),
            ],
            options={
                'verbose_name': 'Layout predefinito dashboard',
                'verbose_name_plural': 'Layout predefinito dashboard',
            },
        ),
        migrations.AddConstraint(
            model_name='defaultdashboardlayout',
            constraint=models.UniqueConstraint(fields=('widget',), name='uniq_default_dashboard_widget'),
        ),
    ]
