# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_defaultdashboardlayout'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_functional_account',
            field=models.BooleanField(
                default=False, verbose_name='Account funzionale',
                help_text=(
                    "Utente di servizio (es. ac.philips, ris.philips, cdd.biotron, jolly.philips) "
                    "usato solo come assegnatario automatico di fallback per i case ServiceNow "
                    "senza un tecnico reale disponibile: resta assegnabile normalmente, ma non "
                    "compare nel pannello Triage né nella vista settimanale assenze, dato che non "
                    "è una persona. Impostabile solo da admin."
                ),
            ),
        ),
    ]
