# Generated by Django 5.2.16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_userprofile_is_functional_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(
                blank=True, null=True, max_length=1,
                choices=[('M', 'Uomo'), ('F', 'Donna')],
                verbose_name='Genere',
                help_text="Usato per personalizzare i saluti (es. widget Meteo). Impostabile solo da admin.",
            ),
        ),
    ]
