# Generated by Django 5.2.17 on 2026-09-09 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_userprofile_theme_remove_navy_temp'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledJobRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_name', models.CharField(max_length=100, unique=True)),
                ('last_run_date', models.DateField()),
            ],
            options={
                'verbose_name': 'Esecuzione job schedulato',
                'verbose_name_plural': 'Esecuzioni job schedulati',
            },
        ),
    ]
