# Generated by Django 5.2.17 on 2026-08-07 12:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0002_reportrequest_status_resolution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrequest',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rifiutato il'),
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='rejected_report_requests', to=settings.AUTH_USER_MODEL, verbose_name='Rifiutato da'),
        ),
        migrations.AddField(
            model_name='reportrequest',
            name='rejection_reason',
            field=models.TextField(blank=True, default='', verbose_name='Motivazione rifiuto'),
        ),
        migrations.AlterField(
            model_name='reportrequest',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved'), ('rejected', 'Rejected')], default='open', max_length=16),
        ),
        migrations.AddIndex(
            model_name='reportrequest',
            index=models.Index(fields=['rejected_by'], name='reportrequest_rejected_by_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrequest',
            index=models.Index(fields=['-rejected_at'], name='reportrequest_rejected_at_idx'),
        ),
    ]
